// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDendqciOtjsWLQe0fo6CEltwa7WsA_h4',
    appId: '1:681567262625:web:1ccc061644a50223ecdde0',
    messagingSenderId: '681567262625',
    projectId: 'minnalmini-5d0bb',
    authDomain: 'minnalmini-5d0bb.firebaseapp.com',
    storageBucket: 'minnalmini-5d0bb.appspot.com',
    measurementId: 'G-SYDZ2QHJGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwzZvyt90SnxjfrhFDnOi-XxHv9A9cxJc',
    appId: '1:681567262625:android:52e2f8f5dd9576acecdde0',
    messagingSenderId: '681567262625',
    projectId: 'minnalmini-5d0bb',
    storageBucket: 'minnalmini-5d0bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8zTDF0kSiax6o8AhfHECSMIubSNiLW8s',
    appId: '1:681567262625:ios:c97486fd07244af6ecdde0',
    messagingSenderId: '681567262625',
    projectId: 'minnalmini-5d0bb',
    storageBucket: 'minnalmini-5d0bb.appspot.com',
    iosClientId: '681567262625-1svqc5ifrcu0k2khouo465bp6435mpr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.minnalmini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8zTDF0kSiax6o8AhfHECSMIubSNiLW8s',
    appId: '1:681567262625:ios:f97892f1849e348fecdde0',
    messagingSenderId: '681567262625',
    projectId: 'minnalmini-5d0bb',
    storageBucket: 'minnalmini-5d0bb.appspot.com',
    iosClientId: '681567262625-4n6dgfpchhcc2tlbkqkf6ptr8n0pe6dn.apps.googleusercontent.com',
    iosBundleId: 'com.example.minnalmini.RunnerTests',
  );
}
